language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install paver
  - pip install .
# command to run tests, e.g. python setup.py test
script: nosetests
notifications:
  irc:
    channels:
      - "irc.nerv.fi#pyfibot"
    skip_join: true
